{{- if and .Values.frontend.enabled .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airsense-api
  labels:
    {{- include "airsense.labels" . | nindent 4 }}
    app.kubernetes.io/component: airsense-api
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  {{- with .Values.frontend.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.frontend.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - {{- with .Values.frontend.ingress.host }}
      host: {{ . | quote }}
      {{- end }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: airsense-api
                port:
                  number: {{ .Values.backend.port }}
{{- end }}
