apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "airsense.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.secret.postgresUser | quote }}
  postgres-password: {{ .Values.secret.postgresPassword | quote }}
  postgres-database: {{ .Values.secret.postgresDatabase | quote }}
  postgres-connection-string: {{ include "airsense.postgresConnectionString" . | quote }}
  postgres-url: {{ include "airsense.postgresUri" . | quote }}
  mqtt-api-password: {{ .Values.secret.mqttApiPassword | quote }}
  firebase-project-name: {{ .Values.secret.firebaseProjectName | quote }}
  firebase-credentials-file-location: {{ .Values.secret.firebaseCredentialsFileLocation | quote }}
{{- if .Values.secret.firebaseCredentialsJson }}
  firebase-service-account.json: |
{{ .Values.secret.firebaseCredentialsJson | nindent 4 }}
{{- end }}
