apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  selector:
    app: emqx
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: dashboard
      port: 18083
      targetPort: 18083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
        - name: emqx
          image: emqx/emqx:latest
          ports:
            - containerPort: 1883
            - containerPort: 18083
          startupProbe:
            tcpSocket:
              port: 1883
            failureThreshold: 60
            periodSeconds: 2
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 768Mi
          volumeMounts:
            - name: emqx-config
              mountPath: /opt/emqx/etc/emqx.conf
              subPath: emqx.conf
      volumes:
        - name: emqx-config
          configMap:
            name: emqx-config
