apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airsense

resources:
  - namespace.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - emqx.yaml
  - api.yaml
  - telemetry-ingestion.yaml
  - automation.yaml
  - notification.yaml

configMapGenerator:
  - name: postgres-initdb
    files:
      - script.sql=postgres-init/script.sql
      - functions.sql=postgres-init/functions.sql
      - data.sql=postgres-init/data.sql
  - name: emqx-config
    files:
      - emqx.conf=emqx.conf

generatorOptions:
  disableNameSuffixHash: true
