apiVersion: v1
kind: Secret
metadata:
  name: airsense-secret
type: Opaque
stringData:
  postgres-user: postgres
  postgres-password: airsense1234
  postgres-database: airsensedb
  postgres-connection-string: Host=postgres;Port=5432;Database=airsensedb;Username=postgres;Password=airsense1234
  mqtt-api-password: airsense-api-secret
  firebase-project-name: ""
  firebase-credentials-file-location: ""
